[pages]
framework = "vite"
pages_build_output_dir = "./dist"
compatibility_date = "2024-01-29"

[build]
command = "node build.mjs"
output_dir = "dist"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"
PACKAGE_MANAGER = "npm"

[pages_build_output_dir]
value = "dist" 