name = "jiu-jitsu-payments"
main = ".cloudflare/workers-site/index.js"
compatibility_date = "2024-01-29"

[build]
command = "npm install && npm run build"
pages_build_output_dir = "dist"
node_bundler = "npm"
node_version = "18.17.1"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"
CI = "true"
NPM_FLAGS = "--legacy-peer-deps"
PACKAGE_MANAGER = "npm"

[site]
bucket = "./dist"

[pages]
framework = "vite"
buildCommand = "npm install && npm run build"
outputDirectory = "dist" 
