[build]
command = "npm install && npm run build"
publish = "dist"
node_bundler = "npm"
node_version = "18.17.1"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"
CI = "true"
NPM_FLAGS = "--legacy-peer-deps" 