[build]
command = "bash ./build.sh"
output_directory = "dist"
base_directory = "/"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"
CI = "true"
NPM_FLAGS = "--legacy-peer-deps"

[site]
bucket = "./dist" 