// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrbbhtuvvweoccyanzsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyYmJodHV2dndlb2NjeWFuenNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMDE1NTAsImV4cCI6MjA1MzU3NzU1MH0.4uZVsh661N1vyIOCmUTzJHIpvKEuyx3uoci-OD0DmSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);